//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteVotacion.ServicioVotacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://votacion/", ConfigurationName="ServicioVotacion.WSVotacion")]
    public interface WSVotacion {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sigla del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://votacion/WSVotacion/obtenerVotacionRequest", ReplyAction="http://votacion/WSVotacion/obtenerVotacionResponse")]
        ClienteVotacion.ServicioVotacion.obtenerVotacionResponse obtenerVotacion(ClienteVotacion.ServicioVotacion.obtenerVotacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://votacion/WSVotacion/obtenerVotacionRequest", ReplyAction="http://votacion/WSVotacion/obtenerVotacionResponse")]
        System.Threading.Tasks.Task<ClienteVotacion.ServicioVotacion.obtenerVotacionResponse> obtenerVotacionAsync(ClienteVotacion.ServicioVotacion.obtenerVotacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerVotacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerVotacion", Namespace="http://votacion/", Order=0)]
        public ClienteVotacion.ServicioVotacion.obtenerVotacionRequestBody Body;
        
        public obtenerVotacionRequest() {
        }
        
        public obtenerVotacionRequest(ClienteVotacion.ServicioVotacion.obtenerVotacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class obtenerVotacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sigla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string formato;
        
        public obtenerVotacionRequestBody() {
        }
        
        public obtenerVotacionRequestBody(string sigla, string formato) {
            this.sigla = sigla;
            this.formato = formato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerVotacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerVotacionResponse", Namespace="http://votacion/", Order=0)]
        public ClienteVotacion.ServicioVotacion.obtenerVotacionResponseBody Body;
        
        public obtenerVotacionResponse() {
        }
        
        public obtenerVotacionResponse(ClienteVotacion.ServicioVotacion.obtenerVotacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class obtenerVotacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double @return;
        
        public obtenerVotacionResponseBody() {
        }
        
        public obtenerVotacionResponseBody(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSVotacionChannel : ClienteVotacion.ServicioVotacion.WSVotacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSVotacionClient : System.ServiceModel.ClientBase<ClienteVotacion.ServicioVotacion.WSVotacion>, ClienteVotacion.ServicioVotacion.WSVotacion {
        
        public WSVotacionClient() {
        }
        
        public WSVotacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSVotacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSVotacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSVotacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteVotacion.ServicioVotacion.obtenerVotacionResponse ClienteVotacion.ServicioVotacion.WSVotacion.obtenerVotacion(ClienteVotacion.ServicioVotacion.obtenerVotacionRequest request) {
            return base.Channel.obtenerVotacion(request);
        }
        
        public double obtenerVotacion(string sigla, string formato) {
            ClienteVotacion.ServicioVotacion.obtenerVotacionRequest inValue = new ClienteVotacion.ServicioVotacion.obtenerVotacionRequest();
            inValue.Body = new ClienteVotacion.ServicioVotacion.obtenerVotacionRequestBody();
            inValue.Body.sigla = sigla;
            inValue.Body.formato = formato;
            ClienteVotacion.ServicioVotacion.obtenerVotacionResponse retVal = ((ClienteVotacion.ServicioVotacion.WSVotacion)(this)).obtenerVotacion(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteVotacion.ServicioVotacion.obtenerVotacionResponse> ClienteVotacion.ServicioVotacion.WSVotacion.obtenerVotacionAsync(ClienteVotacion.ServicioVotacion.obtenerVotacionRequest request) {
            return base.Channel.obtenerVotacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteVotacion.ServicioVotacion.obtenerVotacionResponse> obtenerVotacionAsync(string sigla, string formato) {
            ClienteVotacion.ServicioVotacion.obtenerVotacionRequest inValue = new ClienteVotacion.ServicioVotacion.obtenerVotacionRequest();
            inValue.Body = new ClienteVotacion.ServicioVotacion.obtenerVotacionRequestBody();
            inValue.Body.sigla = sigla;
            inValue.Body.formato = formato;
            return ((ClienteVotacion.ServicioVotacion.WSVotacion)(this)).obtenerVotacionAsync(inValue);
        }
    }
}
