//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteOperaciones.servicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap/", ConfigurationName="servicio.servicio1")]
    public interface servicio1 {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://soap/).
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/servicio1/sumarRequest", ReplyAction="http://soap/servicio1/sumarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteOperaciones.servicio.sumarResponse sumar(ClienteOperaciones.servicio.sumarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/servicio1/sumarRequest", ReplyAction="http://soap/servicio1/sumarResponse")]
        System.Threading.Tasks.Task<ClienteOperaciones.servicio.sumarResponse> sumarAsync(ClienteOperaciones.servicio.sumarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://soap/).
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/servicio1/restarRequest", ReplyAction="http://soap/servicio1/restarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteOperaciones.servicio.restarResponse restar(ClienteOperaciones.servicio.restarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/servicio1/restarRequest", ReplyAction="http://soap/servicio1/restarResponse")]
        System.Threading.Tasks.Task<ClienteOperaciones.servicio.restarResponse> restarAsync(ClienteOperaciones.servicio.restarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://soap/).
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/servicio1/multiplicarRequest", ReplyAction="http://soap/servicio1/multiplicarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteOperaciones.servicio.multiplicarResponse multiplicar(ClienteOperaciones.servicio.multiplicarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/servicio1/multiplicarRequest", ReplyAction="http://soap/servicio1/multiplicarResponse")]
        System.Threading.Tasks.Task<ClienteOperaciones.servicio.multiplicarResponse> multiplicarAsync(ClienteOperaciones.servicio.multiplicarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://soap/).
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/servicio1/dividirRequest", ReplyAction="http://soap/servicio1/dividirResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteOperaciones.servicio.dividirResponse dividir(ClienteOperaciones.servicio.dividirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://soap/servicio1/dividirRequest", ReplyAction="http://soap/servicio1/dividirResponse")]
        System.Threading.Tasks.Task<ClienteOperaciones.servicio.dividirResponse> dividirAsync(ClienteOperaciones.servicio.dividirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumar", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class sumarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public sumarRequest() {
        }
        
        public sumarRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumarResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class sumarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public sumarResponse() {
        }
        
        public sumarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restar", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class restarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public restarRequest() {
        }
        
        public restarRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restarResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class restarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public restarResponse() {
        }
        
        public restarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicar", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class multiplicarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public multiplicarRequest() {
        }
        
        public multiplicarRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplicarResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class multiplicarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public multiplicarResponse() {
        }
        
        public multiplicarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dividir", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class dividirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public dividirRequest() {
        }
        
        public dividirRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="dividirResponse", WrapperNamespace="http://soap/", IsWrapped=true)]
    public partial class dividirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public dividirResponse() {
        }
        
        public dividirResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicio1Channel : ClienteOperaciones.servicio.servicio1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicio1Client : System.ServiceModel.ClientBase<ClienteOperaciones.servicio.servicio1>, ClienteOperaciones.servicio.servicio1 {
        
        public servicio1Client() {
        }
        
        public servicio1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicio1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicio1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicio1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteOperaciones.servicio.sumarResponse ClienteOperaciones.servicio.servicio1.sumar(ClienteOperaciones.servicio.sumarRequest request) {
            return base.Channel.sumar(request);
        }
        
        public int sumar(int a, int b) {
            ClienteOperaciones.servicio.sumarRequest inValue = new ClienteOperaciones.servicio.sumarRequest();
            inValue.a = a;
            inValue.b = b;
            ClienteOperaciones.servicio.sumarResponse retVal = ((ClienteOperaciones.servicio.servicio1)(this)).sumar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteOperaciones.servicio.sumarResponse> ClienteOperaciones.servicio.servicio1.sumarAsync(ClienteOperaciones.servicio.sumarRequest request) {
            return base.Channel.sumarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteOperaciones.servicio.sumarResponse> sumarAsync(int a, int b) {
            ClienteOperaciones.servicio.sumarRequest inValue = new ClienteOperaciones.servicio.sumarRequest();
            inValue.a = a;
            inValue.b = b;
            return ((ClienteOperaciones.servicio.servicio1)(this)).sumarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteOperaciones.servicio.restarResponse ClienteOperaciones.servicio.servicio1.restar(ClienteOperaciones.servicio.restarRequest request) {
            return base.Channel.restar(request);
        }
        
        public int restar(int a, int b) {
            ClienteOperaciones.servicio.restarRequest inValue = new ClienteOperaciones.servicio.restarRequest();
            inValue.a = a;
            inValue.b = b;
            ClienteOperaciones.servicio.restarResponse retVal = ((ClienteOperaciones.servicio.servicio1)(this)).restar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteOperaciones.servicio.restarResponse> ClienteOperaciones.servicio.servicio1.restarAsync(ClienteOperaciones.servicio.restarRequest request) {
            return base.Channel.restarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteOperaciones.servicio.restarResponse> restarAsync(int a, int b) {
            ClienteOperaciones.servicio.restarRequest inValue = new ClienteOperaciones.servicio.restarRequest();
            inValue.a = a;
            inValue.b = b;
            return ((ClienteOperaciones.servicio.servicio1)(this)).restarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteOperaciones.servicio.multiplicarResponse ClienteOperaciones.servicio.servicio1.multiplicar(ClienteOperaciones.servicio.multiplicarRequest request) {
            return base.Channel.multiplicar(request);
        }
        
        public int multiplicar(int a, int b) {
            ClienteOperaciones.servicio.multiplicarRequest inValue = new ClienteOperaciones.servicio.multiplicarRequest();
            inValue.a = a;
            inValue.b = b;
            ClienteOperaciones.servicio.multiplicarResponse retVal = ((ClienteOperaciones.servicio.servicio1)(this)).multiplicar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteOperaciones.servicio.multiplicarResponse> ClienteOperaciones.servicio.servicio1.multiplicarAsync(ClienteOperaciones.servicio.multiplicarRequest request) {
            return base.Channel.multiplicarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteOperaciones.servicio.multiplicarResponse> multiplicarAsync(int a, int b) {
            ClienteOperaciones.servicio.multiplicarRequest inValue = new ClienteOperaciones.servicio.multiplicarRequest();
            inValue.a = a;
            inValue.b = b;
            return ((ClienteOperaciones.servicio.servicio1)(this)).multiplicarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteOperaciones.servicio.dividirResponse ClienteOperaciones.servicio.servicio1.dividir(ClienteOperaciones.servicio.dividirRequest request) {
            return base.Channel.dividir(request);
        }
        
        public int dividir(int a, int b) {
            ClienteOperaciones.servicio.dividirRequest inValue = new ClienteOperaciones.servicio.dividirRequest();
            inValue.a = a;
            inValue.b = b;
            ClienteOperaciones.servicio.dividirResponse retVal = ((ClienteOperaciones.servicio.servicio1)(this)).dividir(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteOperaciones.servicio.dividirResponse> ClienteOperaciones.servicio.servicio1.dividirAsync(ClienteOperaciones.servicio.dividirRequest request) {
            return base.Channel.dividirAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteOperaciones.servicio.dividirResponse> dividirAsync(int a, int b) {
            ClienteOperaciones.servicio.dividirRequest inValue = new ClienteOperaciones.servicio.dividirRequest();
            inValue.a = a;
            inValue.b = b;
            return ((ClienteOperaciones.servicio.servicio1)(this)).dividirAsync(inValue);
        }
    }
}
